### ISSUE TITLE
Information Gathering regarding the current process of SLSS student application

### ISSUE THREAD

**Issue by mariane21** [IT3A-2016/TechKnights#13]
Conduct an interview to some SLSS personnel and list down the important details to be gathered. Make sure that the interview is permitted by the director or signed by our adviser.

**Comment by louiealmeda** [comment]
comment findings here

**Comment by jhanning29** [comment]
last January 23 2017, we conducted an interview on SLSS office for the preparation of our proposed system. because of the busy schedule or because our schedule did not met ms. salcedo's sched, we are not able to interview her. but instead ask ms. jane about the project. we dscovered that they need a system that will help them lighten their work in separating the students information from another. separate the scholars from non-scholars and also will separate the students whose parents are working abroad. they allow us to use that problem as our system. and we will conduct a second part of interview for the informations of the students. attached photo is the form that every student has to fill-up once they are officially enrolled in the school. 
![16443225_1522723047756961_796974566_n.jpg](https://zube.io/files/IT3A-2016/722ed3160e28f81b7b5b488a87058c75.jpeg)
